[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
methods = { path = "../methods" }
risc0-zkvm = { version = "2.0.2" }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
bincode = "1.3.3"
clap = { version = "4.5.37", features = ["derive"] }
